### ISSUE TITLE
フォントが標準のフォントになってしまう

### ISSUE THREAD

**Issue by kti-sxb** [yoshikixxxx/poderosa-connectprofile-plugin#1]
こんにちわ

テキスト色と背景色はオプション設定のものが反映されているようなのですが、
フォント自体がオプション設定のものが無視されて標準のものになっているような気がします。

オプション設定の内容を引き継ぐようにならないでしょうか？

**Comment by yoshikixxxx** [comment]
こんにちは。
お返事が大変遅くなり申し訳ありません。

内容について了解しました。
うまくできるかどうかわかりませんが修正してみます。

またご連絡差し上げます。

**Comment by yoshikixxxx** [comment]
久々にコードを読んでみましたが、そもそも本プラグインにフォント設定のロジックが存在していないため、それ自体の機能を追加する形となってしまいますので少しお時間がかかるかもしれません。
が、今後のためにもあったほうがよいかと思いますので修正してみます。

※オプション設定というのは本プラグインのオプション設定を指していますでしょうか？

**Comment by yoshikixxxx** [comment]
こんにちは。

フォント設定を含む表示オプション設定に対応したv2.0をリリースしましたので本件はクローズとさせて頂きます。

尚、本件の変更に伴いプロファイルデータの仕様が変更されていますので必ずPoderosa設定ファイル（options.conf）をバックアップ後にバージョンアップをしてください。

当方でテストは行っておりますが、万一不具合等があればご連絡ください。

よろしくお願いします。
